### ISSUE TITLE
Server side

### ISSUE THREAD

**Issue by SkippTekk** [TSSN/Sinful-Skies#1]
hey guys, just loaded the server files. and it's rejecting my client due to TwistedTweaks, possible fix for this or no?

**Comment by artdude543** [comment]
Oh my fault with that download I sent ya, grab [this](https://ci.artdude.uk/job/Twisted-Tweaks/lastSuccessfulBuild/artifact/build/libs/twistedtweaks-0.0.8-15.jar) and replace it with the one in the folder currently.

**Comment by artdude543** [comment]
v1.3 I should have the server configs setup, so I would personally wait till thats released :)
