### ISSUE TITLE
mining speed 0 with TiCon pickaxe

### ISSUE THREAD

**Issue by JorisvanRoy** [TSSN/Sinful-Skies#11]
when i added a diamond hammer for smashing to my flint pickaxe with wooden binding and a stick i got mining speed 0

**Comment by MindlessPuppetz** [comment]
Are you talking about a diamond hammer from ex nihilo?

**Comment by artdude543** [comment]
This is an intentional feature from the mod to remove mining levels from the tool. Using the tool xp system you can regain some of it back. But adding the upgrades (Smashing, Crooking) will debuff your tool. It's intentional and won't be changing.
