### ISSUE TITLE
enviromine not working when rejoining a server

### ISSUE THREAD

**Issue by JorisvanRoy** [TSSN/Sinful-Skies#12]
when i rejoin my 1 man hamachi server i first need to kill myself before enviromine is doing the thirst and body temperature thing

**Comment by MindlessPuppetz** [comment]
This is a known bug and has already been fixed in the next version.

**Comment by artdude543** [comment]
I would also recommend to not use hamachi for Minecraft servers they are known to cause networking issues with some mods and its the most insecure software in the world.
