### ISSUE TITLE
Rubber tree leaves can't be vein mined

### ISSUE THREAD

**Issue by RyanTheAllmighty** [TSSN/Sinful-Skies#14]
As the title says, I use a copper mattock, I can veinmine oak leaves but not MFR rubber tree leaves. Is this intentional or is it reality!

**Comment by artdude543** [comment]
This is not a bug but just a non-configured block it is added in 1.5 though! So don't fear a fix is coming your way soon.

**Comment by RyanTheAllmighty** [comment]
Still happening with veinmine on tinkers construct axes

**Comment by RyanTheAllmighty** [comment]
@artdude543

**Comment by artdude543** [comment]
Ahh okay will fix!
