### ISSUE TITLE
Wooden swords

### ISSUE THREAD

**Issue by SkippTekk** [TSSN/Sinful-Skies#15]
@RyanTheAllMighty tried to make a item with wooden sword for wooden spikes. there is no recipe for making wooden swords.

**Comment by artdude543** [comment]
Hmm okay will fix that for 1.5

**Comment by SkippTekk** [comment]
thank you thank you :)

**Comment by artdude543** [comment]
Recipe has been added for the sword now, 1.5 should be out in the next few days (hopefully)
