### ISSUE TITLE
Wood burn

### ISSUE THREAD

**Issue by Junglistbeast** [TSSN/Sinful-Skies#18]
Wood burns at a faster rate in the furnace vs the slab furnace

**Comment by SkippTekk** [comment]
why would you use a FURNACE and not a SLAB one?

**Comment by SkippTekk** [comment]
btw, just get 5 cobble, make a slap and combine only 2 of the slabs together to make another set of slabs for cobble. BAM you got a slab furnace :)

**Comment by artdude543** [comment]
I have tested this and can't replicate it with an array of woods. What setup did you have to produce this issue?

**Comment by Junglistbeast** [comment]
Because resources ain't an issue once you've got a cobble gen :)

Oak Wood as fuel in both - In slab furnace will burn Oak wood into 6 charcoal - in a normal furnace will burn Oak wood into 1 charcoal.

**Comment by artdude543** [comment]
Yeah I found the issue. This is going to be a pain to fix as the fuel value is hardcoded into the mod.

**Comment by artdude543** [comment]
This has been temporarily fixed by removing the recipes to the effect blocks until it's fixed on their side.
