### ISSUE TITLE
Harvesting crops

### ISSUE THREAD

**Issue by Junglistbeast** [TSSN/Sinful-Skies#19]
I've harvested a couple of crops and sometimes (not all), when right clicking they don't produce anything?

i.e. right click pineapple, returns to 0% growth but didn't give me a pineapple.

It has happened to potatoes as as well. Strange.....

**Comment by artdude543** [comment]
Hmm, I will have to load up a world to see. It was working fine on the dev server could be something fixed in the new build or a fluke thing. I will test in a bit and get back to you.

**Comment by PixelPrincess80** [comment]
I have had this happen several times to me as well.

**Comment by artdude543** [comment]
This is not necessarily a bug but an intended feature. You are not 100% assured of getting something extra back from the crop growing. This all down to chances on getting extra returns from crop growing. This may need to be tweaked but from my extensive testing the values on return (on average) are fine and you are still able to live.

**Comment by Junglistbeast** [comment]
I agree with the levels of return they are fine, I'm certainly producing more.  I just thought it was best to raise in case it wasn't intended :+1:

**Comment by artdude543** [comment]
Okay well I'm going to close this issue for now. If the values seem off (Like you get nothing back a lot of the time) re-open the issue and we will look into it again.
