### ISSUE TITLE
Saw/Planks Recipe

### ISSUE THREAD

**Issue by Junglistbeast** [TSSN/Sinful-Skies#2]
The Forge Micro Blocks Saw + Wood recipe doesn't create 4 planks.  It only creates the FMB Wood Slab, looks like there is a recipe conflict.

Saw is currently above wood block, in twisted sin it is on the left.

**Comment by artdude543** [comment]
This has been fixed as of version v1.3-beta which may be pushed later tonight or in the morning on the following day.
