### ISSUE TITLE
Sound muffler doesn't work

### ISSUE THREAD

**Issue by RyanTheAllmighty** [TSSN/Sinful-Skies#20]
The sound muffler from Extra Utilities doesn't seem to work. The recipe is there, right clicking does nothing, redstone signal does nothing, the thermal expansion machines still make noise, it doesn't seem to affect anything

**Comment by artdude543** [comment]
I'll look into.

**Comment by RyanTheAllmighty** [comment]
It was very very odd. I relogged, tried everything and it didn't seem to work.

It muffled the chest opening and closing sounds, but not thermal expansion pulverizers.

I'll update this tomorrow with the new update if it was only a single time hiccup or not

**Comment by artdude543** [comment]
It could be that the muffler does not support TE, as I know TE use their our sound handler I think so he muffler may not understand the "sound"

**Comment by RyanTheAllmighty** [comment]
If that's the case, that's a real shame. The noise from pulverizers is horrid :\ Again I'll check again in the morning, worse case I can just move my pulverizer setup away from my main living area

**Comment by artdude543** [comment]
Yeah it looks like the muffler does not understand the sound. Also does not stop sound from other blocks / entities too. (Like carts) So this is a shame really I had big plans for the muffler in my world lol

I'll poke around with devs to see if the muffler can be "upgraded" to work with other sound sources.

**Comment by artdude543** [comment]
Yeah so after poking / testing it seems the block does not support other types of sound sources but maybe will be added at some point. We shall see. _crosses fingers_
