### ISSUE TITLE
Veinmine 1.6

### ISSUE THREAD

**Issue by SkippTekk** [TSSN/Sinful-Skies#21]
Hey guys, i tried to do Veinmine with a Crook and it won't do it. bug or just a glitch? or maybe you guys just complete nurfed and it won't work BibleThump

**Comment by SkippTekk** [comment]
never mind i just looked in the config and i need a god damn tool that has veinmine in it FailFish

**Comment by MindlessPuppetz** [comment]
Bone crooks get veinminer enchant upon crafting as well

**Comment by SkippTekk** [comment]
so regular crooks don't get it?

**Comment by SkippTekk** [comment]
so i gotta use the enchant ment to get it?

**Comment by MindlessPuppetz** [comment]
Wood crooks don't get it, bone does. Hammers made of stone and higher get it. Tinkers has to have the correct modifiers applied for it. Glowstone
