### ISSUE TITLE
Can't make reusable safari net

### ISSUE THREAD

**Issue by RyanTheAllmighty** [TSSN/Sinful-Skies#24]
The recipe for a reusable safari net requires a porta spawner which has no recipe.

Is this intended or a bug?

**Comment by artdude543** [comment]
I'll look into this today, we're planning on making the end update soon. But I'll release a patch before hand to fix the recipe issues and some config tweaks.

**Comment by RyanTheAllmighty** [comment]
Alright let me know when fixed and updated so I can play again :)

**Comment by artdude543** [comment]
Just an update on this we're waiting for the new Tinkers update before pushing a new build :)

**Comment by artdude543** [comment]
This has been fixed in the dev (dev, dev) version being pushed today.
