### ISSUE TITLE
Autonomous Activator + Water

### ISSUE THREAD

**Issue by kojul** [TSSN/Sinful-Skies#25]
We spawned in a deep ocean and I set up an activator to fill water buckets and was going to set up auto smelting for them. But the thing is that the autonomous activator does not respect the saltiness of water. So it will fill water buckets with clean water while in an ocean/deep ocean/beach biome.

**Comment by artdude543** [comment]
(CC @Funwayguy) I think when I brought this up that its something not do-able. As your code it not tracking fake players? This is not a "game breaking" bug as the recipes to make the Activator are harder to create.
