### ISSUE TITLE
Hunger - Too slow to require food. 

### ISSUE THREAD

**Issue by Junglistbeast** [TSSN/Sinful-Skies#3]
Hunger seems to lower quite slowly, probably needs to lower faster.

Simply put - I haven't died of hunger!

**Comment by artdude543** [comment]
@MindlessPuppetz What do you think about this?

**Comment by SkippTekk** [comment]
Well it would make the new comers (like me) very frustrated if there trying to play it if they always die of hunger. A little quicker would make it a challenge though :)

**Comment by artdude543** [comment]
Beginning game you don't do a lot of moving around to lose the hunger but once you get a platform going you will start to use more, so it's a matter of working out if its worth taking down a few to make it harder. (When you have a base it's fine as you should have plenty of food source) but beginning game losing hunger faster might be too much for some players. _Cough_ @RyanTheAllmighty :P

**Comment by Junglistbeast** [comment]
Just as long as it doesn't go to Agrarian Skies level of usage!  It may be muddied slightly that you die a lot to start with from ents.  That takes care of very early game hunger, as you don't eat. It's once you stop getting owned by ents it feels a bit slow. I may be wrong, still early into testing!

**Comment by SkippTekk** [comment]
Well. The ends are really gonna kick the hard core players butt. literally. And I almost spat out my drink @artdude543

**Comment by MindlessPuppetz** [comment]
Hmm, I will have to look into this. Hunger is slow to dwindle at first because of not moving around much. That will increase once you get a bigger platform/base. Will need more testing I'm afraid.

**Comment by MindlessPuppetz** [comment]
Also, unless we add in more features to Twisted Tweaks, the only way to alter the food depletion speed is to add in Hunger Overhaul, which we have previously said no to. Might revisit that mod at a later date depending on testing results.

**Comment by Junglistbeast** [comment]
I'll add more once i've spent more time testing, It is a difficult one.  Initially it seems maybe to easy it may change once the issue of being killed by ents is controlled and the speed that you can get a mattock.  I feel that once you have a mattock hunger may become a none issue.  

I still need to test if using the mattock on grass gives seeds?

**Comment by SkippTekk** [comment]
I'll be playing the pack today. So ill see if it does or not.

**Comment by Junglistbeast** [comment]
Tested it today mattock doesn't give seeds on grass... 

I have remembered the path to some easy early foods.  Stock, which can be used on its own or easily into, seed soup, spider eye soup and cactus soup along with apple juice and apples cooked silkworms.  

If you are lucky and get some other seeds (I got strawberry) from some dirt sifting the ability to vary the food types isn't too bad. 

That being said I think dying a lot helps slow down the need for food to begin with.  One thing I have noticed is sifting doesn't seem to use up hunger? Is that right?

**Comment by SkippTekk** [comment]
Sifting I think personally should be the same speed as running. Not jumping. But running.

**Comment by artdude543** [comment]
We designed it so you would get the seeds from sifting dirt (Including Pams base foods to make the seeds) The new update will prevent you getting drops from breaking grass, so you're forced to sieve and grow plants to get more seeds ;)

**Comment by artdude543** [comment]
This should be fixed as of the new build (v1.5) we did some tweaks and add another mod to help with using hunger beginning game.

**Comment by RyanTheAllmighty** [comment]
Any estimate as to when 1.5 will be out?

**Comment by MindlessPuppetz** [comment]
It is out now

**Comment by RyanTheAllmighty** [comment]
Good news. Are the AE2 stencils in there now?

**Comment by MindlessPuppetz** [comment]
Yes. Use NEI to see the recipes
