### ISSUE TITLE
Sag Mill vs Pulverizer

### ISSUE THREAD

**Issue by Junglistbeast** [TSSN/Sinful-Skies#4]
The SAG mill is much cheaper than the pulverizer - the latter requiring diamond to build the SAG mill does not.  Pulverizer also uses a lot more ingots to create.

Change SAG mill to use something other than flint in recipe? changing the capacitor recipe for the machine frame on the SAG mill may break other machine costs.

**Comment by artdude543** [comment]
The recipe for the SAG Mill has been changed to better suit the tier system.
