### ISSUE TITLE
Skip Smeltery?

### ISSUE THREAD

**Issue by Junglistbeast** [TSSN/Sinful-Skies#5]
Bear with me on this... You can skip the need for a tinkers smeltery to make the first alloys by using the the AE2 grindstone and following the below steps;

1:- Furnace ex nihilo Sand/Gravel
2:- AE2 Grindstone the Ingot back to Dust
3:- Blend Dust in crafting table to alloy dust
4:- Furnace Alloy Dust 
5:- Win? - Alloy ingot without using a smeltery

**Comment by artdude543** [comment]
This has been fixed by disabling the AE2 Grindstone, will wait for the next dev release to see if their are other ways of getting around the smeltery.

**Comment by artdude543** [comment]
This has been fixed since the last version closing this now :)
