### ISSUE TITLE
Quest book or objectives list???

### ISSUE THREAD

**Issue by PixelPrincess80** [TSSN/Sinful-Skies#7]
Is there a quest book or objectives list or something out there to help guide us?

**Comment by MindlessPuppetz** [comment]
Not yet, we will be adding some custom books/achievements in the future, but we are also trying to stay away from telling people how they should play, too many packs are doing that now in my opinion. Minecraft is a sandbox game and I want to keep that in mind with my pack, I want it difficult, but still open for different ways of being played.

**Comment by MindlessPuppetz** [comment]
I have written and added version 1 of the beginners guide book to v1.5 Beta of the pack.
