### ISSUE TITLE
Enviromine

### ISSUE THREAD

**Issue by Junglistbeast** [TSSN/Sinful-Skies#8]
It seems if the acid rain is on enviromine doesn't update with thirst or heat.  When the rain stopped it started updating again.

**Comment by Junglistbeast** [comment]
It's not acid rain - something else......

**Comment by artdude543** [comment]
This is known bug with EnviroMine and possibly fixed in the next version of the pack.

**Comment by artdude543** [comment]
This should be fixed as of version 1.5 of the pack.
